Repository awaazo/awaazo, pull requests merged in 2023-11, with the labels that each got.

#129 Refactoring/file storage
  .gitignore
  Backend/Backend.Tests/ProfileTests.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Infrastructure/FileStorageHelper.cs
  Backend/Backend/Services/ProfileService.cs
  docker-compose.yml
Labels: ✨goal: improvement

#131 Feature/podcast management
  Backend/Backend/Backend.csproj
  Backend/Backend/Controllers/EpisodeController.cs
  Backend/Backend/Controllers/FileController.cs
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Requests/EpisodeRequest.cs
  Backend/Backend/Controllers/Requests/PodcastRequest.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Services/EpisodeService.cs
  Backend/Backend/Services/FileService.cs
  Backend/Backend/Services/Interfaces/IFileService.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: ⭐ goal: addition

#132 Refactoring/podcast testing
  Backend/Backend.Tests/Backend.Tests.csproj
  Backend/Backend/Controllers/EpisodeController.cs
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Models/Podcast.cs
  Backend/Backend/Services/FileService.cs
  Backend/Backend/Services/PodcastService.cs
  backend/Backend.Tests/PodcastTests.cs
Labels: 🛠️ goal: fix, ✨goal: improvement, 🟨 priority: medium

#136 homepage - Add changes to Frontend branch
  frontend/components/home/ExploreGenres.tsx
  frontend/components/home/ForYou.tsx
  frontend/components/home/ForYouSection.tsx
  frontend/components/home/PodcastTicket.tsx
  frontend/components/home/RecentlyUploaded.tsx
  frontend/components/profile/MyEpisodes.tsx
  frontend/components/shared/Navbar.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/Main.tsx
  frontend/pages/Setup.tsx
  frontend/pages/auth/Login.tsx
  frontend/pages/index.tsx
Labels: ✨goal: improvement, 🟨 priority: medium

#135 Added playlist backend api routes #26
  Backend/Backend.Tests/PlaylistTests.cs
  Backend/Backend/Controllers/PlaylistController.cs
  Backend/Backend/Controllers/Requests/PlaylistRequests.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Middlewares/ValidateUser.cs
  Backend/Backend/Migrations/20231027222343_firstMigration.Designer.cs
  Backend/Backend/Migrations/20231103155618_secondMigration.Designer.cs
  Backend/Backend/Migrations/20231103155618_secondMigration.cs
  Backend/Backend/Migrations/20231103203451_thirdMigration.Designer.cs
  Backend/Backend/Migrations/20231103203451_thirdMigration.cs
  Backend/Backend/Migrations/20231103205022_fourthMigration.Designer.cs
  Backend/Backend/Migrations/20231103205022_fourthMigration.cs
  Backend/Backend/Migrations/20231103214610_fifthMigration.cs
  Backend/Backend/Migrations/20231104220846_sixthMigration.Designer.cs
  Backend/Backend/Migrations/20231104220846_sixthMigration.cs
  Backend/Backend/Migrations/20231107193441_firstMigration.Designer.cs
  Backend/Backend/Migrations/20231107193441_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  Backend/Backend/Models/Playlist.cs
  Backend/Backend/Models/User.cs
  Backend/Backend/Program.cs
  Backend/Backend/Services/PlaylistService.cs
Labels: ⭐ goal: addition

#149 linked endpoint for rate and review Podcasts
  .gitignore
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Requests/SocialRequests.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Controllers/Responses/SocialResponses.cs
  Backend/Backend/Controllers/SocialController.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20231109174942_firstMigration.Designer.cs
  Backend/Backend/Migrations/20231109174942_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  Backend/Backend/Models/Comment.cs
  Backend/Backend/Models/Follow.cs
  Backend/Backend/Models/Like.cs
  Backend/Backend/Models/Podcast.cs
  Backend/Backend/Program.cs
  Backend/Backend/Services/Interfaces/ISocialService.cs
  Backend/Backend/Services/PodcastService.cs
  Backend/Backend/Services/SocialService.cs
  frontend/components/rating/RatingComponent.tsx
  frontend/components/rating/ReviewComponent.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/ReviewsHelper.tsx
  frontend/pages/Main.tsx
  frontend/pages/MyPodcasts.tsx
  frontend/pages/profile/MyPodcasts.tsx
  frontend/utilities/Requests.tsx
  frontend/utilities/Responses.tsx
Labels: 🧑‍💻 dev stroy

#146 Added Endpoints for getting other user's profiles
  Backend/Backend/Controllers/AuthController.cs
  Backend/Backend/Controllers/BaseController.cs
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Controllers/Responses/UserReponses.cs
  Backend/Backend/Infrastructure/ControllerHelper.cs
  Backend/Backend/Migrations/20231108151147_secondMigration.Designer.cs
  Backend/Backend/Migrations/20231108151147_secondMigration.cs
  Backend/Backend/Models/User.cs
  Backend/Backend/Services/Interfaces/IProfileService.cs
  Backend/Backend/Services/ProfileService.cs
Labels: 🧑‍💻 dev stroy

#153 Feature/get podcast by genre endpoint
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Controllers/Responses/SocialResponses.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: 🧑‍💻 dev stroy

#156 Removed the duplicate BackendTest Folder
  Backend/Backend.Tests/NotificationTests.cs
  Backend/Backend.Tests/PodcastTests.cs
Labels: 🛠️ goal: fix, 🟩 priority: low, Backend

#157 CI/CD Setup/Development
  .github/workflows/deploy-services.yml
  .github/workflows/e2e.yml
  .gitignore
  Backend/Backend/Backend.csproj
  Backend/Backend/Program.cs
  Backend/Backend/wwwroot/swagger-ui/SwaggerDark.css
  Backend/Backend/wwwroot/swagger-ui/custom.js
  Backend/Backend/wwwroot/swagger-ui/resources/148492079.ico
  frontend/Dockerfile
  frontend/__tests__/Login.test.js
  frontend/__tests__/RestHelper.test.js
  frontend/__tests__/Signup.test.js
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/RestHelper.tsx
  package-lock.json
Labels: 🧑‍💻 dev stroy

#161 Added Token Validation for GoogleSSO
  Backend/Backend.Tests/AuthTests.cs
  Backend/Backend/Controllers/AuthController.cs
  Backend/Backend/Controllers/Requests/AuthRequests.cs
  Backend/Backend/Controllers/Responses/UserReponses.cs
  Backend/Backend/Services/AuthService.cs
  Backend/Backend/Services/Interfaces/IAuthService.cs
  frontend/components/shared/Navbar.tsx
  frontend/helpers/AuthHelper.tsx
  frontend/pages/api/auth/[...nextauth].ts
  frontend/utilities/Requests.tsx
  frontend/utilities/Responses.tsx
Labels: 🛠️ goal: fix

#163 Adding tests to certain controllers, and general refactoring
  Backend/Backend.Tests/PodcastTests.cs
  Backend/Backend.Tests/ProfileTests.cs
  Backend/Backend/Controllers/BaseController.cs
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Controllers/SocialController.cs
  Backend/Backend/Migrations/20231113193500_firstMigration.Designer.cs
  Backend/Backend/Migrations/20231113193500_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  Backend/Backend/Services/Interfaces/IProfileService.cs
  Backend/Backend/Services/PodcastService.cs
  Backend/Backend/Services/ProfileService.cs
Labels: 🛠️ goal: fix, ✨goal: improvement, Backend

#159 Fixed Navbar mobile view Bug
  frontend/components/shared/Navbar.tsx
Labels: 🛠️ goal: fix

#164 Feature/podcast comments
  Backend/Backend.Tests/NotificationTests.cs
  Backend/Backend.Tests/PodcastTests.cs
  Backend/Backend.Tests/ProfileTests.cs
  Backend/Backend.Tests/SubscriptionTest.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Controllers/Requests/SocialRequests.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Controllers/Responses/SocialResponses.cs
  Backend/Backend/Controllers/Responses/UserReponses.cs
  Backend/Backend/Controllers/SocialController.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20231114210957_firstMigration.Designer.cs
  Backend/Backend/Migrations/20231114210957_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  Backend/Backend/Models/Comment.cs
  Backend/Backend/Models/Episode.cs
  Backend/Backend/Models/Files.cs
  Backend/Backend/Models/Like.cs
  Backend/Backend/Models/User.cs
  Backend/Backend/Services/Interfaces/IProfileService.cs
  Backend/Backend/Services/Interfaces/ISocialService.cs
  Backend/Backend/Services/PodcastService.cs
  Backend/Backend/Services/ProfileService.cs
  Backend/Backend/Services/SocialService.cs
  frontend/components/home/ContinueListening.tsx
  frontend/components/myPodcast/MyEpisodes.tsx
  frontend/components/myPodcast/MyPodcast.tsx
  frontend/components/rating/RatingComponent.tsx
  frontend/components/rating/ReviewComponent.tsx
  frontend/components/social/commentComponent.tsx
  frontend/components/social/likeComponent.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/SocialHelper.tsx
  frontend/pages/profile/EditProfile.tsx
  frontend/utilities/Interfaces.tsx
  frontend/utilities/Requests.tsx
  frontend/utilities/Responses.tsx
  frontend/utilities/SampleData.tsx
Labels: ⭐ goal: addition

#177 US #175, Adding basic Logging
  .gitignore
  Backend/Backend.Tests/AuthTests.cs
  Backend/Backend.Tests/NotificationTests.cs
  Backend/Backend.Tests/PodcastTests.cs
  Backend/Backend.Tests/ProfileTests.cs
  Backend/Backend.Tests/SubscriptionTest.cs
  Backend/Backend/Controllers/AuthController.cs
  Backend/Backend/Controllers/NotificationController.cs
  Backend/Backend/Controllers/PlaylistController.cs
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Controllers/SocialController.cs
  Backend/Backend/Controllers/SubscriptionController.cs
  Backend/Backend/Infrastructure/FileLogger.cs
  Backend/Backend/Program.cs
Labels: 🔢 points: 2, 🟧 priority: high, 🧑‍💻 dev stroy, Backend

#186 Improved code legibility and removed unused imports
  frontend/components/CreatePodcastHeader.tsx
  frontend/components/explore/Episode.tsx
  frontend/components/explore/PodcastCard.tsx
  frontend/components/explore/PodcastOverview.tsx
  frontend/components/explore/Podcasts.tsx
  frontend/components/explore/Reviews.tsx
  frontend/components/explore/UserCard.tsx
  frontend/components/home/ContinueListening.tsx
  frontend/components/home/ExploreGenres.tsx
  frontend/components/home/ForYou.tsx
  frontend/components/home/PodcastTicket.tsx
  frontend/components/home/RecentlyUploaded.tsx
  frontend/components/myPodcast/EditEpisodeForm.tsx
  frontend/components/myPodcast/EditPodcastForm.tsx
  frontend/components/myPodcast/MyEpisodes.tsx
  frontend/components/myPodcast/MyPodcast.tsx
  frontend/components/player/Bookmarks.tsx
  frontend/components/player/ChatBot.tsx
  frontend/components/player/CoverArt.tsx
  frontend/components/player/Sections.tsx
  frontend/components/player/Transcripts.tsx
  frontend/components/profile/Header.tsx
  frontend/components/profile/MyEpisodes.tsx
  frontend/components/profile/Podcasts.tsx
  frontend/components/rating/RatingComponent.tsx
  frontend/components/rating/ReviewComponent.tsx
  frontend/components/shared/Navbar.tsx
  frontend/components/social/commentComponent.tsx
  frontend/components/social/likeComponent.tsx
  frontend/pages/Create.tsx
  frontend/pages/CreateAI.tsx
  frontend/pages/Explore.tsx
  frontend/pages/MyPodcasts.tsx
  frontend/pages/NewPodcast.tsx
  frontend/pages/NowPlaying.tsx
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/pages/profile/EditProfile.tsx
  frontend/pages/profile/MyPodcasts.tsx
  frontend/pages/profile/MyProfile.tsx
Labels: ✨goal: improvement

#191 Removed GPU requirement
  .github/workflows/e2e.yml
  .github/workflows/frontend.yml
  Backend/Backend/Controllers/BookmarkController.cs
  Backend/Backend/Controllers/Requests/BookmarkRequests.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20231118222721_firstMigration.Designer.cs
  Backend/Backend/Migrations/20231118222721_firstMigration.cs
  Backend/Backend/Models/Bookmark.cs
  Backend/Backend/Program.cs
  Backend/Backend/Services/BookmarkService.cs
  docker-compose.ci.yml
Labels: 🛠️ goal: fix

#181 Merging Profile authentication verification and Podcast editing on profile
  frontend/components/profile/Podcasts.tsx
  frontend/pages/profile/MyProfile.tsx
Labels: ⭐ goal: addition, ✨goal: improvement

#199 Test suite refactored
  frontend/components/myPodcast/MyEpisodes.tsx
  frontend/cypress.config.ts
  frontend/cypress/e2e/auth/Login.cy.tsx
  frontend/cypress/e2e/auth/Logout.cy.tsx
  frontend/cypress/e2e/auth/Register.cy.tsx
  frontend/cypress/e2e/podcast/Episode.cy.tsx
  frontend/cypress/e2e/podcast/Podcast.cy.tsx
  frontend/cypress/e2e/podcast/Review.cy.tsx
  frontend/cypress/e2e/profile/EditProfile.cy.tsx
  frontend/cypress/fixtures/file_paths.d.ts
  frontend/cypress/fixtures/file_paths.json
  frontend/cypress/fixtures/images/crazy_symbols.jpg
  frontend/cypress/fixtures/images/f2_car.jpg
  frontend/cypress/index.d.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/tsconfig.json
  frontend/pages/Create.tsx
Labels: ✨goal: improvement

#207 Addition of IsLiked Endpoint
  .github/workflows/build-services.yml
  .github/workflows/e2e.yml
  Backend/Backend/Controllers/SocialController.cs
  Backend/Backend/Services/Interfaces/ISocialService.cs
  Backend/Backend/Services/SocialService.cs
  docker-compose.frontend.yml
  frontend/cypress.config.ts
  frontend/cypress/e2e/auth/Register.cy.tsx
  frontend/cypress/e2e/podcast/Episode.cy.tsx
  frontend/cypress/support/commands.ts
Labels: ⭐ goal: addition, 🧑‍💻 dev stroy

#209 Fixed Navbar Search Bug
  frontend/components/shared/Navbar.tsx
Labels: 🛠️ goal: fix

#212 Fixed Likes and Comment Visibility & Refactored code and styles
  frontend/components/explore/Episode.tsx
  frontend/components/home/PodcastTicket.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/components/social/commentComponent.tsx
  frontend/components/social/likeComponent.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/SocialHelper.tsx
  frontend/utilities/Responses.tsx
Labels: 🛠️ goal: fix

#211 Feature/podcast subscription
  frontend/components/explore/MySubscriptions.tsx
  frontend/components/explore/PodcastOverview.tsx
  frontend/components/explore/Subscription.tsx
  frontend/components/shared/Navbar.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/NotificationsHelper.tsx
  frontend/helpers/SubscribeHelper.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/notification/NotificationFilter.tsx
  frontend/pages/notification/Notifications.tsx
  frontend/pages/notification/SortButton.tsx
  frontend/pages/profile/MyProfile.tsx
  frontend/utilities/Interfaces.tsx
  frontend/utilities/Responses.tsx
Labels: 🟨 priority: medium, 🧑‍💻 dev stroy

#213 Feature/User Profiles
  frontend/components/Cards/PodcastCard.tsx
  frontend/components/Cards/UserCard.tsx
  frontend/components/explore/Subscription.tsx
  frontend/components/explore/UserCard.tsx
  frontend/components/home/ForYou.tsx
  frontend/components/home/RecentlyUploaded.tsx
  frontend/components/profile/MyEpisodes.tsx
  frontend/components/profile/MyProfile/MyEpisodes.tsx
  frontend/components/profile/MyProfile/MyHeader.tsx
  frontend/components/profile/MyProfile/MyPlaylists.tsx
  frontend/components/profile/MyProfile/MyPodcasts.tsx
  frontend/components/profile/Podcasts.tsx
  frontend/components/profile/UserProfile/UserEpisodes.tsx
  frontend/components/profile/UserProfile/UserHeader.tsx
  frontend/components/profile/UserProfile/UserPlaylists.tsx
  frontend/components/profile/UserProfile/UserPodcasts.tsx
  frontend/components/shared/Navbar.tsx
  frontend/cypress/e2e/auth/Register.cy.tsx
  frontend/cypress/e2e/podcast/Episode.cy.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/PodcastHelper.tsx
  frontend/helpers/UserProfileHelper.tsx
  frontend/pages/Create.tsx
  frontend/pages/Explore/Genre/[genre].tsx
  frontend/pages/Explore/Search.tsx
  frontend/pages/MyPodcasts.tsx
  frontend/pages/profile/MyPodcasts.tsx
  frontend/pages/profile/MyProfile.tsx
  frontend/pages/profile/[id].tsx
  frontend/utilities/Interfaces.tsx
  frontend/utilities/Responses.tsx
Labels: 👤user story

#218 Bug/fix notifications
  frontend/components/shared/Navbar.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/notification/Notifications.tsx
  frontend/pages/profile/MyProfile.tsx
Labels: 🛠️ goal: fix

#220 Fixed issue with Podcast endpoints
  Backend/Backend/Models/Podcast.cs
  Backend/Backend/Services/PodcastService.cs
Labels: 🛠️ goal: fix

#221 Fixed Episode upload to prevent duplication
  frontend/pages/Create.tsx
Labels: 🛠️ goal: fix

#224 Dev/liked episodes endpoint + Playlist refactoring
  Backend/Backend.Tests/AuthTests.cs
  Backend/Backend.Tests/PlaylistTests.cs
  Backend/Backend/Controllers/PlaylistController.cs
  Backend/Backend/Controllers/Requests/PlaylistRequests.cs
  Backend/Backend/Controllers/Responses/PlaylistResponses.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20231130230902_firstMigration.Designer.cs
  Backend/Backend/Migrations/20231130230902_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  Backend/Backend/Models/Comment.cs
  Backend/Backend/Models/Episode.cs
  Backend/Backend/Models/Like.cs
  Backend/Backend/Models/Playlist.cs
  Backend/Backend/Models/User.cs
  Backend/Backend/Program.cs
  Backend/Backend/Services/AuthService.cs
  Backend/Backend/Services/Interfaces/IPlaylistService.cs
  Backend/Backend/Services/PlaylistService.cs
  Backend/Backend/Services/SocialService.cs
Labels: ✨goal: improvement
