Repository awaazo/awaazo, pull requests merged in 2023-12, with the labels that each got.

#225 Feature/progress bar
  Backend/Backend/Program.cs
  Backend/Backend/Services/SectionService.cs
  backend/Backend/Migrations/20231130201447_xMigration.Designer.cs
  backend/Backend/Migrations/20231130201447_xMigration.cs
  frontend/cypress/e2e/podcast/Episode.cy.tsx
  frontend/helpers/PodcastHelper.tsx
  frontend/pages/Create.tsx
Labels: 👤user story

#227 Addition of Unit Tests for Playlist Controller & Service
  Backend/Backend.Tests/GlobalUsings.cs
  Backend/Backend.Tests/PlaylistControllerTests.cs
  Backend/Backend.Tests/PlaylistServiceTests.cs
  Backend/Backend.Tests/PlaylistTests.cs
  Backend/Backend/Controllers/PlaylistController.cs
  Backend/Backend/Services/PlaylistService.cs
Labels: ✨goal: improvement

#253 Added Get API endpoint to get the watch history of a given episode #203
  Backend/Backend.Tests/PodcastTests.cs
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: ⭐ goal: addition

#256 Merging Bookmarks to Main
  frontend/components/bookmarks/bookmarkComponent.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/helpers/BookmarksHelper.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/SocialHelper.tsx
  frontend/utilities/Requests.tsx
  frontend/utilities/Responses.tsx
Labels: ⭐ goal: addition

#259 Added API route to change a user's password #245
  Backend/Backend.Tests/ProfileTests.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Controllers/Requests/ProfileRequests.cs
  Backend/Backend/Services/Interfaces/IProfileService.cs
  Backend/Backend/Services/ProfileService.cs
  frontend/cypress/e2e/podcast/Episode.cy.tsx
  frontend/cypress/e2e/social/Comment.cy.tsx
  frontend/cypress/e2e/social/Like.cy.tsx
Labels: ⭐ goal: addition, 🧑‍💻 dev stroy

#261 Feat/adjecent episode ids
  Backend/Backend.Tests/NotificationTests.cs
  Backend/Backend.Tests/PlaylistServiceTests.cs
  Backend/Backend.Tests/PodcastTests.cs
  Backend/Backend/Controllers/NotificationController.cs
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Services/Interfaces/INotificationService.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/NotificationService.cs
  Backend/Backend/Services/PlaylistService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: ✨goal: improvement

#264 Feature/tts
  Python/Dockerfile
  Python/requirements.txt
  Python/server.py
  Python/text_to_speech_service/tts.py
  docker-compose.macos.yml
  docker-compose.yml
Labels: ⭐ goal: addition
