Repository awaazo/awaazo, pull requests merged in 2024-03, with the labels that each got.

#417 Fix/edit playlist
  frontend/components/playlist/PlaylistMenu.tsx
  frontend/components/shared/Sidebar.tsx
  frontend/helpers/PlaylistHelper.tsx
  frontend/types/Interfaces.tsx
Labels: 🛠️ goal: fix

#413 Addition of a Toggled Side Panel
  Backend/Backend/Controllers/Requests/PodcastRequests.cs
  Backend/Backend/Migrations/20240228063641_AddedReportEntity.Designer.cs
  Backend/Backend/Migrations/20240228063641_AddedReportEntity.cs
  Backend/Backend/Migrations/20240303170013_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240303170013_firstMigration.cs
  frontend/.prettierrc
  frontend/components/CreatorHub/AddEpisode.tsx
  frontend/components/CreatorHub/SectionsPlayingBar.tsx
  frontend/components/cards/EpisodeCard.tsx
  frontend/components/cards/EpisodeMenu.tsx
  frontend/components/explore/Episode.tsx
  frontend/components/explore/ExploreGenres.tsx
  frontend/components/home/ForYou.tsx
  frontend/components/home/PodcastTicket.tsx
  frontend/components/interactionHub/Bookmarks.tsx
  frontend/components/interactionHub/ChatBot.tsx
  frontend/components/interactionHub/Comments.tsx
  frontend/components/interactionHub/Likes.tsx
  frontend/components/interactionHub/Share.tsx
  frontend/components/interactionHub/buttons/BookmarksButton.tsx
  frontend/components/interactionHub/buttons/ChatBotButton.tsx
  frontend/components/interactionHub/buttons/CommentButton.tsx
  frontend/components/playerbar/Menu.tsx
  frontend/components/playlist/PlaylistMenu.tsx
  frontend/components/playlist/PlaylistOverview.tsx
  frontend/components/rating/RatingComponent.tsx
  frontend/components/shared/ChatBot.tsx
  frontend/components/shared/Panel.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/components/shared/Sidebar.tsx
  frontend/components/social/Bookmarks.tsx
  frontend/components/social/Comments.tsx
  frontend/cypress/e2e/podcast/PlayerBar.cy.tsx
  frontend/cypress/e2e/social/Comment.cy.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/SocialHelper.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/types/Interfaces.tsx
  frontend/types/Responses.tsx
  frontend/utilities/ChatBotContext.tsx
  frontend/utilities/PanelContext.tsx
Labels: ✨goal: improvement

#416 Feat/tip-jar
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Controllers/WalletController.cs
  Backend/Backend/Services/Interfaces/IWalletServices.cs
  Backend/Backend/Services/SocialService.cs
  Backend/Backend/Services/StripeServices.cs
  Backend/Backend/Services/WalletServices.cs
  docker-compose.macos.m1.yml
  frontend/components/cards/EpisodeCard.tsx
  frontend/components/cards/TransactionCard.tsx
  frontend/components/cards/WalletPodcastCard.tsx
  frontend/components/explore/PodcastOverview.tsx
  frontend/components/interactionHub/Tipjar.tsx
  frontend/components/playerbar/Menu.tsx
  frontend/components/playlist/PlaylistOverview.tsx
  frontend/components/profile/MyProfile/MyEpisodes.tsx
  frontend/components/profile/UserProfile/UserEpisodes.tsx
  frontend/components/shared/Navbar.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/components/wallet/Last5DaysBalace.tsx
  frontend/components/wallet/Last5DaysEarnings.tsx
  frontend/components/wallet/MostGiftedEpsiode.tsx
  frontend/components/wallet/MostGiftedPodcast.tsx
  frontend/components/wallet/Transactions.tsx
  frontend/components/wallet/Withdraw.tsx
  frontend/cypress/e2e/podcast/Playlists.cy.tsx
  frontend/cypress/e2e/search/Search.cy.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/PaymentHelper.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/Explore/Search.tsx
  frontend/pages/NowPlaying/[EpisodeId].tsx
  frontend/pages/Playlist/[playlistId].tsx
  frontend/pages/Wallet/index.tsx
  frontend/types/Interfaces.tsx
  frontend/types/Requests.tsx
  frontend/types/Responses.tsx
Labels: Backend, Muhammad Mubashir 491

#421 fixed random book mark apperance in playerbar menu , added tipjar to …
  frontend/components/interactionHub/Tipjar.tsx
  frontend/components/interactionHub/buttons/TipjarButton.tsx
  frontend/components/playerbar/Menu.tsx
  frontend/components/shared/Panel.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/components/wallet/Last5DaysBalace.tsx
  frontend/components/wallet/Last5DaysEarnings.tsx
  frontend/components/wallet/MostGiftedEpsiode.tsx
  frontend/components/wallet/MostGiftedPodcast.tsx
  frontend/components/wallet/Transactions.tsx
  frontend/components/wallet/Withdraw.tsx
  frontend/styles/AppTheme.tsx
Labels: 🛠️ goal: fix

#422 Fix/python deps
  Python/.dockerignore
  Python/Dockerfile
  Python/__init__.py
  Python/assistant_service/__init__.py
  Python/assistant_service/ingest.py
  Python/requirements.txt
  Python/rvc_service/__init__.py
  Python/text_to_episode_script/__init__.py
  Python/text_to_speech_service/__init__.py
  Python/transcription_service/__init__.py
  docker-compose.yml
Labels: 🛠️ goal: fix, 🟨 priority: medium

#425 Fix/removing migrations from build - MERGE PLZ!!
  .github/workflows/build-backend-image.yml
  .github/workflows/build-services.yml
  Backend/Backend/Migrations/20240306173423_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240306173423_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
Labels: 🛠️ goal: fix

#429 Feature/user analytics endpoints
  Backend/Backend.Tests/AnalyticControllerTests.cs
  Backend/Backend.Tests/AnalyticServiceTests.cs
  Backend/Backend/Controllers/AnalyticController.cs
  Backend/Backend/Controllers/Responses/AnalyticResponses.cs
  Backend/Backend/Services/AnalyticService.cs
  Backend/Backend/Services/Interfaces/IAnalyticService.cs
Labels: ⭐ goal: addition, Mathieu Trudeau SOEN 491

#430 Feat/history endpoints
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Requests/PodcastRequests.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: ✨goal: improvement, Backend

#428 Episode Transcript Implementation
  .github/workflows/backend.yml
  Backend/Backend/Migrations/20240304191244_InitialCreate.Designer.cs
  Backend/Backend/Migrations/20240304191244_InitialCreate.cs
  Backend/Backend/Migrations/20240306173423_firstMigration.cs
  frontend/components/CreatorHub/ManageTranscript.tsx
  frontend/components/CreatorHub/MyEpisodes.tsx
  frontend/components/CreatorHub/TranscriptPlayingBar.tsx
  frontend/components/nowPlaying/Transcript.tsx
  frontend/pages/NowPlaying/[EpisodeId].tsx
Labels: ✨goal: improvement

#433 Feature/e2e mobile
  frontend/components/cards/UserCard.tsx
  frontend/cypress.config.ts
  frontend/cypress/e2e/desktop/auth/AuthPrompt.cy.tsx
  frontend/cypress/e2e/desktop/auth/Login.cy.tsx
  frontend/cypress/e2e/desktop/auth/Logout.cy.tsx
  frontend/cypress/e2e/desktop/auth/Register.cy.tsx
  frontend/cypress/e2e/desktop/podcast/Episode.cy.tsx
  frontend/cypress/e2e/desktop/podcast/PlayerBar.cy.tsx
  frontend/cypress/e2e/desktop/podcast/Playlists.cy.tsx
  frontend/cypress/e2e/desktop/podcast/Podcast.cy.tsx
  frontend/cypress/e2e/desktop/podcast/Review.cy.tsx
  frontend/cypress/e2e/desktop/podcast/Section.cy.tsx
  frontend/cypress/e2e/desktop/profile/ChangePassword.cy.tsx
  frontend/cypress/e2e/desktop/profile/EditProfile.cy.tsx
  frontend/cypress/e2e/desktop/profile/Notification.cy.tsx
  frontend/cypress/e2e/desktop/search/Search.cy.tsx
  frontend/cypress/e2e/desktop/social/Comment.cy.tsx
  frontend/cypress/e2e/desktop/social/Like.cy.tsx
  frontend/cypress/e2e/login.cy.ts
  frontend/cypress/e2e/mobile/auth/MobileLogin.cy.tsx
  frontend/cypress/e2e/mobile/auth/MobileLogout.cy.tsx
  frontend/cypress/e2e/mobile/auth/MobileRegister.cy.tsx
  frontend/cypress/e2e/mobile/podcast/MobileEpisode.cy.tsx
  frontend/cypress/e2e/mobile/podcast/MobilePlayerBar.cy.tsx
  frontend/cypress/e2e/mobile/podcast/MobilePodcast.cy.tsx
  frontend/cypress/e2e/mobile/profile/MobileChangePassword.cy.tsx
  frontend/cypress/e2e/mobile/profile/MobileEditProfile.cy.tsx
  frontend/cypress/index.d.ts
  frontend/cypress/support/commands.ts
Labels: ✨goal: improvement

#432 Added Recommendation endpoint
  Backend/Backend.Tests/Backend.Tests.csproj
  Backend/Backend/Backend.csproj
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Requests/PodcastRequests.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: ⭐ goal: addition, Backend

#434 improving transcript on Nowplaying and edit transcript in Creatorhub
  Backend/Backend/Migrations/20240304191244_InitialCreate.cs
  Backend/Backend/Migrations/20240318192051_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240318192051_firstMigration.cs
  frontend/components/CreatorHub/ManageTranscript.tsx
  frontend/components/nowPlaying/Bookmarks.tsx
  frontend/components/nowPlaying/Transcript.tsx
  frontend/helpers/PodcastHelper.tsx
  frontend/styles/AppTheme.tsx
  frontend/types/Interfaces.tsx
  frontend/types/Requests.tsx
Labels: ✨goal: improvement, 🔢 points: 8, 🟧 priority: high

#439 Fixed bug where Report Service was always returning validation error
  Backend/Backend/Controllers/ReportController.cs
  Backend/Backend/Controllers/Requests/AdminPanelRequests.cs
  Backend/Backend/Middlewares/ValidateAdmin.cs
  Backend/Backend/Services/AdminPanelService.cs
  Backend/Backend/Services/ReportService.cs
Labels: Backend, SOEN 491 - 40131283 (Shadi Jiha)

#441 Feat/podcast highlights
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
  frontend/components/CreatorHub/MyEpisodes.tsx
  frontend/components/highlights/HighlightList.tsx
  frontend/components/highlights/HighlightScrollPage.tsx
  frontend/components/highlights/HighlightTicket.tsx
  frontend/components/highlights/Highlights.tsx
  frontend/components/highlights/highlightForm.tsx
  frontend/components/home/Home.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/HighlightHelper.tsx
  frontend/helpers/SocialHelper.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/types/Interfaces.tsx
  frontend/types/Requests.tsx
  frontend/types/Responses.tsx
Labels: ⭐ goal: addition

#435 Fixed bug where PodcastService.GetPodcastsByTagsAsync was vunerable to SQL injection
  Backend/Backend.Tests/PodcastTests.cs
  Backend/Backend/Services/PodcastService.cs
Labels: 🛠️ goal: fix, 🟧 priority: high, Backend

#444 updated episode card
  README.md
  frontend/components/cards/EpisodeCard.tsx
  frontend/components/cards/WalletPodcastCard.tsx
  frontend/components/explore/PodcastOverview.tsx
  frontend/components/home/Home.tsx
  frontend/components/home/PodcastTicket.tsx
  frontend/components/home/RecentlyUploaded.tsx
  frontend/components/interactionHub/Likes.tsx
  frontend/components/interactionHub/buttons/CommentButton.tsx
  frontend/components/playlist/EpisodeCardForPlaylist.tsx
  frontend/components/playlist/PlaylistOverview.tsx
  frontend/components/profile/MyProfile/MyEpisodes.tsx
  frontend/components/profile/UserProfile/UserEpisodes.tsx
  frontend/components/wallet/MostGiftedEpsiode.tsx
  frontend/pages/Explore/Search.tsx
  frontend/pages/Playlist/[playlistId].tsx
  frontend/public/icons/AwaazoAdminPannel.tsx
  frontend/public/icons/AwaazoLogo.tsx
  frontend/public/icons/Bookmark.tsx
  frontend/public/icons/Cards.tsx
  frontend/public/icons/Chat.tsx
  frontend/public/icons/Check.tsx
  frontend/public/icons/Document.tsx
  frontend/public/icons/Dollar.tsx
  frontend/public/icons/Dots.tsx
  frontend/public/icons/Home.tsx
  frontend/public/icons/Like.tsx
  frontend/public/icons/Lock.tsx
  frontend/public/icons/Logout.tsx
  frontend/public/icons/Mail.tsx
  frontend/public/icons/Pen.tsx
  frontend/public/icons/Play.tsx
  frontend/public/icons/PlayIcon.tsx
  frontend/public/icons/Plays.tsx
  frontend/public/icons/Search.tsx
  frontend/public/icons/Send.tsx
  frontend/public/icons/Settings.tsx
  frontend/public/icons/SpeakerFull.tsx
  frontend/public/icons/Time.tsx
  frontend/public/icons/Trash.tsx
  frontend/public/icons/Unlock.tsx
  frontend/public/icons/User.tsx
  frontend/public/icons/Warning.tsx
  frontend/styles/AppTheme.tsx
Labels: 🛠️ goal: fix, ✨goal: improvement

#451 Feature/ai summaries
  frontend/components/CreatorHub/ManageTranscript.tsx
  frontend/components/CreatorHub/MyEpisodes.tsx
  frontend/components/interactionHub/ChatBot.tsx
  frontend/components/nowPlaying/Transcript.tsx
Labels: ✨goal: improvement

#452 Fix/highlights
  frontend/components/CreatorHub/MyEpisodes.tsx
  frontend/components/highlights/FullScreenHighlight.tsx
  frontend/components/highlights/HighlightScrollPage.tsx
  frontend/components/highlights/HighlightTicket.tsx
  frontend/components/highlights/Highlights.tsx
  frontend/components/highlights/highlightForm.tsx
  frontend/components/interactionHub/Likes.tsx
  frontend/components/interactionHub/buttons/CommentButton.tsx
Labels: ⭐ goal: addition, 🛠️ goal: fix

#460 Added recommendation endpoint
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Requests/PodcastRequests.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: Backend

#459 Feat/admin podcast recommendations
  Backend/Backend/Controllers/AdminPanelController.cs
  Backend/Backend/Controllers/Requests/AdminPanelRequests.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Models/Podcast.cs
  Backend/Backend/Services/AdminPanelService.cs
Labels: Backend
