Repository awaazo/awaazo, pull requests merged in 2024-01, with the labels that each got.

#262 Fix/reviews and subscription issues
  frontend/components/explore/PodcastOverview.tsx
  frontend/components/explore/Reviews.tsx
  frontend/components/explore/Subscription.tsx
  frontend/cypress.config.ts
  frontend/cypress/e2e/podcast/PlayerBar.cy.tsx
  frontend/cypress/e2e/podcast/Review.cy.tsx
  frontend/pages/Explore/[id].tsx
Labels: 🛠️ goal: fix

#272 Added RVC (Realistic Voice Cloning) API Endpoint to the Python Server
  .gitignore
  Python/.dockerignore
  Python/Dockerfile
  Python/rvc_service/.env
  Python/rvc_service/LICENSE
  Python/rvc_service/assets/Synthesizer_inputs.pth
  Python/rvc_service/assets/hubert/.gitignore
  Python/rvc_service/assets/hubert/hubert_inputs.pth
  Python/rvc_service/assets/rmvpe/.gitignore
  Python/rvc_service/assets/rmvpe/rmvpe_inputs.pth
  Python/rvc_service/configs/config.py
  Python/rvc_service/configs/v1/32k.json
  Python/rvc_service/configs/v1/40k.json
  Python/rvc_service/configs/v1/48k.json
  Python/rvc_service/configs/v2/32k.json
  Python/rvc_service/configs/v2/48k.json
  Python/rvc_service/infer/lib/audio.py
  Python/rvc_service/infer/lib/infer_pack/attentions.py
  Python/rvc_service/infer/lib/infer_pack/commons.py
  Python/rvc_service/infer/lib/infer_pack/models.py
  Python/rvc_service/infer/lib/infer_pack/modules.py
  Python/rvc_service/infer/lib/infer_pack/transforms.py
  Python/rvc_service/infer/lib/jit/get_rmvpe.py
  Python/rvc_service/infer/lib/rmvpe.py
  Python/rvc_service/infer/modules/train/preprocess.py
  Python/rvc_service/infer/modules/vc/__init__.py
  Python/rvc_service/infer/modules/vc/modules.py
  Python/rvc_service/infer/modules/vc/pipeline.py
  Python/rvc_service/infer/modules/vc/utils.py
  Python/rvc_service/requirements.txt
  Python/rvc_service/rvc.py
  Python/server.py
Labels: ⭐ goal: addition

#289 fixed color theme issue , and a minor bug fix
  frontend/components/cards/PlaylistCard.tsx
  frontend/components/explore/Episode.tsx
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/styles/AppTheme.tsx
  frontend/styles/ColorModeFix.tsx
Labels: 🛠️ goal: fix

#292 Added Annotations + Share Component
  frontend/components/cards/EpisodeCard.tsx
  frontend/components/nowPlaying/AnnotationForm.tsx
  frontend/components/nowPlaying/AnnotationList.tsx
  frontend/components/nowPlaying/PodCue.tsx
  frontend/components/playlist/PlaylistOverview.tsx
  frontend/components/social/shareComponent.tsx
  frontend/helpers/AnnotationHelper.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/pages/NowPlaying/[EpisodeId].tsx
  frontend/utilities/Requests.tsx
  frontend/utilities/Responses.tsx
Labels: ⭐ goal: addition

#293 Feature/tortoise tts
  .gitignore
  Python/.dockerignore
  Python/Dockerfile
  Python/requirements.txt
  Python/rvc_service/requirements.txt
  Python/server.py
  Python/text_to_speech_service/requirements.txt
  Python/text_to_speech_service/tortoise/api_fast.py
  Python/text_to_speech_service/tortoise/data/mel_norms.pth
  Python/text_to_speech_service/tortoise/models/__init__.py
  Python/text_to_speech_service/tortoise/models/activations.py
  Python/text_to_speech_service/tortoise/models/alias_free_torch/__init__.py
  Python/text_to_speech_service/tortoise/models/alias_free_torch/act.py
  Python/text_to_speech_service/tortoise/models/alias_free_torch/filter.py
  Python/text_to_speech_service/tortoise/models/alias_free_torch/resample.py
  Python/text_to_speech_service/tortoise/models/arch_util.py
  Python/text_to_speech_service/tortoise/models/autoregressive.py
  Python/text_to_speech_service/tortoise/models/autoregressive_old.py
  Python/text_to_speech_service/tortoise/models/bigvgan.py
  Python/text_to_speech_service/tortoise/models/classifier.py
  Python/text_to_speech_service/tortoise/models/clvp.py
  Python/text_to_speech_service/tortoise/models/cvvp.py
  Python/text_to_speech_service/tortoise/models/diffusion_decoder.py
  Python/text_to_speech_service/tortoise/models/hifigan_decoder.py
  Python/text_to_speech_service/tortoise/models/random_latent_generator.py
  Python/text_to_speech_service/tortoise/models/stream_generator.py
  Python/text_to_speech_service/tortoise/models/transformer.py
  Python/text_to_speech_service/tortoise/models/vocoder.py
  Python/text_to_speech_service/tortoise/models/xtransformers.py
  Python/text_to_speech_service/tortoise/tokenizer.json
  Python/text_to_speech_service/tortoise/utils/__init__.py
  Python/text_to_speech_service/tortoise/utils/audio.py
  Python/text_to_speech_service/tortoise/utils/device.py
  Python/text_to_speech_service/tortoise/utils/diffusion.py
  Python/text_to_speech_service/tortoise/utils/stft.py
  Python/text_to_speech_service/tortoise/utils/text.py
  Python/text_to_speech_service/tortoise/utils/tokenizer.py
  Python/text_to_speech_service/tortoise/utils/torch_intermediary.py
  Python/text_to_speech_service/tortoise/utils/typical_sampling.py
  Python/text_to_speech_service/tortoise/utils/wav2vec_alignment.py
  Python/text_to_speech_service/tts.py
  Python/transcription_service/stt.py
  docker-compose.yml
Labels: ⭐ goal: addition

#294 Disappearing Podcast after review/rating fix
  Backend/Backend/Services/PodcastService.cs
Labels: 🛠️ goal: fix

#297 Fixed podcast delete error
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20240116003604_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240116003604_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
Labels: 🛠️ goal: fix

#273 Added API routes to reset forgotten password
  .gitignore
  Backend/Backend.Tests/ProfileTests.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Controllers/Requests/ProfileRequests.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20240116164534_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240116164534_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  Backend/Backend/Models/ForgetPasswordToken.cs
  Backend/Backend/Program.cs
  Backend/Backend/Services/EmailService.cs
  Backend/Backend/Services/Interfaces/IProfileService.cs
  Backend/Backend/Services/ProfileService.cs
Labels: 🟧 priority: high, 🧑‍💻 dev stroy, Backend

#305 with /podcast/metric API where
  Backend/Backend/Services/PodcastService.cs
Labels: 🛠️ goal: fix

#306 Improvement/test overhaul
  Backend/Backend/Migrations/20240116202411_zMigrations.Designer.cs
  Backend/Backend/Migrations/20240116202411_zMigrations.cs
  frontend/cypress.config.ts
  frontend/cypress/e2e/auth/Register.cy.tsx
  frontend/cypress/e2e/podcast/Episode.cy.tsx
  frontend/cypress/e2e/podcast/PlayerBar.cy.tsx
  frontend/cypress/e2e/podcast/Podcast.cy.tsx
  frontend/cypress/e2e/podcast/Review.cy.tsx
  frontend/cypress/e2e/podcast/Section.cy.tsx
  frontend/cypress/e2e/profile/EditProfile.cy.tsx
  frontend/cypress/e2e/profile/Notification.cy.tsx
  frontend/cypress/e2e/search/Search.cy.tsx
  frontend/cypress/e2e/social/Comment.cy.tsx
  frontend/cypress/e2e/social/Like.cy.tsx
  frontend/cypress/index.d.ts
  frontend/cypress/support/commands.ts
Labels: ✨goal: improvement

#313 Feat/search filter functionality
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Requests/PlaylistRequests.cs
  Backend/Backend/Controllers/Requests/PodcastRequests.cs
  Backend/Backend/Controllers/Responses/PlaylistResponses.cs
  Backend/Backend/Migrations/20240116202411_zMigrations.Designer.cs
  Backend/Backend/Migrations/20240116202411_zMigrations.cs
  Backend/Backend/Migrations/20240119181320_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240119181320_firstMigration.cs
  Backend/Backend/Models/Playlist.cs
  Backend/Backend/Models/Podcast.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PlaylistService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: Backend

#316 Feature/change password
  Backend/Backend/Migrations/20240122144031_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240122144031_firstMigration.cs
  frontend/components/bookmarks/CreateBookmarkModule.tsx
  frontend/components/profile/MyProfile/ChangePasswordForm.tsx
  frontend/components/profile/MyProfile/MyHeader.tsx
  frontend/components/shared/Navbar.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/components/social/commentComponent.tsx
  frontend/cypress.config.ts
  frontend/cypress/e2e/podcast/Episode.cy.tsx
  frontend/cypress/e2e/podcast/Podcast.cy.tsx
  frontend/cypress/e2e/profile/ChangePassword.cy.tsx
  frontend/cypress/e2e/search/Search.cy.tsx
  frontend/cypress/index.d.ts
  frontend/cypress/support/commands.ts
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/UserProfileHelper.tsx
  frontend/pages/profile/EditProfile.tsx
  frontend/pages/profile/MyProfile.tsx
  frontend/styles/AppTheme.tsx
  frontend/utilities/Requests.tsx
  frontend/utilities/Responses.tsx
Labels: ⭐ goal: addition

#321 Finishing CD
  Backend/Backend.Tests/SectionTest.cs
  Backend/Backend/Program.cs
Labels: ✨goal: improvement, 🟥 priority: critical

#323 creating working docker-compose for amd graphics
  docker-compose.amd.yml
Labels: 🛠️ goal: fix

#322 [301] Added a checkEmail API endpoint
  Backend/Backend/Controllers/AuthController.cs
  Backend/Backend/Controllers/Requests/AuthRequests.cs
  Backend/Backend/Controllers/Requests/ProfileRequests.cs
  Backend/Backend/Migrations/20240122183947_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240122183947_firstMigration.cs
  Backend/Backend/Services/AuthService.cs
  Backend/Backend/Services/EmailService.cs
  Backend/Backend/Services/Interfaces/IAuthService.cs
  Backend/Backend/Services/PlaylistService.cs
  Backend/Backend/Services/PodcastService.cs
  Backend/Backend/Services/ProfileService.cs
Labels: ⭐ goal: addition, Backend

#327 Improvement/backend logging
  Backend/Backend.Tests/AuthTests.cs
  Backend/Backend.Tests/GlobalUsings.cs
  Backend/Backend.Tests/NotificationTests.cs
  Backend/Backend.Tests/PlaylistControllerTests.cs
  Backend/Backend.Tests/SectionTest.cs
  Backend/Backend.Tests/SubscriptionTest.cs
  Backend/Backend/Controllers/AnnotationController.cs
  Backend/Backend/Controllers/AuthController.cs
  Backend/Backend/Controllers/BookmarkController.cs
  Backend/Backend/Controllers/NotificationController.cs
  Backend/Backend/Controllers/PlaylistController.cs
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Controllers/SectionController.cs
  Backend/Backend/Controllers/SocialController.cs
  Backend/Backend/Controllers/SubscriptionController.cs
Labels: ✨goal: improvement

#326 Adding bookmark text limits and improving UI
  frontend/components/bookmarks/CreateBookmarkModule.tsx
Labels: ✨goal: improvement

#319 Create helpers and response modules for episode save watch history
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/PodcastHelper.tsx
  frontend/utilities/Interfaces.tsx
  frontend/utilities/PlayerContext.tsx
  frontend/utilities/Requests.tsx
  frontend/utilities/Responses.tsx
Labels: ⭐ goal: addition

#318 Adding bookmarks and episode transcript to nowplaying page
  frontend/components/nowPlaying/Bookmarks.tsx
  frontend/components/nowPlaying/Transcripts.tsx
  frontend/pages/NowPlaying/[EpisodeId].tsx
Labels: ⭐ goal: addition

#329 Improvement/transcript endpoints
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: ✨goal: improvement

#320 Fix fetch podcasts episodes
  frontend/components/annotations/AnnotationForm.tsx
  frontend/components/annotations/AnnotationList.tsx
  frontend/components/home/ForYou.tsx
  frontend/components/home/RecentlyUploaded.tsx
  frontend/components/myPodcast/MyEpisodes.tsx
  frontend/components/nowPlaying/AnnotationList.tsx
  frontend/components/nowPlaying/PodCue.tsx
  frontend/components/playlist/PlaylistMenu.tsx
  frontend/components/playlist/PlaylistOverview.tsx
  frontend/components/profile/MyProfile/MyEpisodes.tsx
  frontend/components/profile/MyProfile/MyPodcasts.tsx
  frontend/components/profile/MyProfile/MySubscriptions.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/components/social/shareComponent.tsx
  frontend/pages/CreatorHub/MyPodcasts.tsx
  frontend/pages/NowPlaying/[EpisodeId].tsx
  frontend/styles/AppTheme.tsx
Labels: 🧑‍💻 dev stroy

#341 Changed the sentForgotPasswordEmail to /auth
  Backend/Backend.Tests/AuthTests.cs
  Backend/Backend.Tests/ProfileTests.cs
  Backend/Backend/Controllers/AuthController.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Services/AuthService.cs
  Backend/Backend/Services/Interfaces/IAuthService.cs
  Backend/Backend/Services/Interfaces/IProfileService.cs
  Backend/Backend/Services/ProfileService.cs
Labels: ✨goal: improvement, 🔢 points: 1, 🟩 priority: low, Backend

#335 Fixed bug where prodcast metric was always returning 0. Added more metrics
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Controllers/Responses/SocialResponses.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20240125171817_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240125171817_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
Labels: 🛠️ goal: fix, Backend

#344 Fix logout button
  frontend/components/shared/Navbar.tsx
  frontend/helpers/AuthHelper.tsx
Labels: 🛠️ goal: fix

#345 Fix/rvc
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Migrations/20240125195616_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240125195616_firstMigration.cs
  Backend/Backend/Services/PodcastService.cs
  Python/rvc_service/infer/lib/jit/get_rmvpe.py
  Python/rvc_service/infer/modules/vc/pipeline.py
  frontend/components/shared/PlayerBar.tsx
  frontend/cypress/e2e/podcast/PlayerBar.cy.tsx
  frontend/cypress/e2e/profile/EditProfile.cy.tsx
Labels: 🛠️ goal: fix

#360 Comprehensive Mobile Optimization and UI Fixes for Enhanced User Experience
  Backend/Backend/Migrations/20240129195853_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240129195853_firstMigration.cs
  backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  frontend/components/CreatorHub/EditEpisode.tsx
  frontend/components/CreatorHub/EditPodcast.tsx
  frontend/components/CreatorHub/MyPodcast.tsx
  frontend/components/cards/EpisodeCard.tsx
  frontend/components/cards/EpisodeMenu.tsx
  frontend/components/cards/GenreCard.tsx
  frontend/components/cards/PlaylistCard.tsx
  frontend/components/cards/UserCard.tsx
  frontend/components/explore/Episode.tsx
  frontend/components/explore/PodcastOverview.tsx
  frontend/components/home/ExploreGenres.tsx
  frontend/components/home/ForYou.tsx
  frontend/components/home/RecentlyUploaded.tsx
  frontend/components/notification/Notifications.tsx
  frontend/components/playlist/PlaylistMenu.tsx
  frontend/components/profile/MyProfile/MyEpisodes.tsx
  frontend/components/profile/MyProfile/MyHeader.tsx
  frontend/components/profile/MyProfile/MyPlaylists.tsx
  frontend/components/profile/MyProfile/MyPodcasts.tsx
  frontend/components/profile/UserProfile/UserEpisodes.tsx
  frontend/components/profile/UserProfile/UserHeader.tsx
  frontend/components/shared/Navbar.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/components/shared/Sidebar.tsx
  frontend/cypress.config.ts
  frontend/cypress/e2e/auth/Logout.cy.tsx
  frontend/cypress/e2e/auth/Register.cy.tsx
  frontend/cypress/e2e/podcast/Episode.cy.tsx
  frontend/cypress/e2e/podcast/PlayerBar.cy.tsx
  frontend/cypress/e2e/podcast/Playlists.cy.tsx
  frontend/cypress/e2e/podcast/Podcast.cy.tsx
  frontend/cypress/e2e/podcast/Review.cy.tsx
  frontend/cypress/e2e/podcast/Section.cy.tsx
  frontend/cypress/e2e/profile/ChangePassword.cy.tsx
  frontend/cypress/e2e/profile/EditProfile.cy.tsx
  frontend/cypress/e2e/profile/Notification.cy.tsx
  frontend/cypress/e2e/search/Search.cy.tsx
  frontend/cypress/e2e/social/Comment.cy.tsx
  frontend/cypress/e2e/social/Like.cy.tsx
  frontend/cypress/support/commands.ts
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/NotificationsHelper.tsx
  frontend/helpers/PlaylistHelper.tsx
  frontend/helpers/PodcastHelper.tsx
  frontend/pages/CreatorHub/CreatePodcast.tsx
  frontend/pages/Explore/Search.tsx
  frontend/pages/Notifications/MyNotifications.tsx
  frontend/pages/Notifications/Notifications.tsx
  frontend/pages/Playlist/[playlistId].tsx
  frontend/pages/Playlist/index.tsx
  frontend/pages/profile/MyProfile.tsx
  frontend/pages/profile/[id].tsx
  frontend/utilities/Requests.tsx
  frontend/utilities/Responses.tsx
Labels: ✨goal: improvement

#362 fixed playlist routing on mobile bug , removed redundant profile icon, checking e2e testing
  frontend/components/shared/Sidebar.tsx
Labels: 🛠️ goal: fix

#348 NowPlaying - Fixing timestamp display and icon and adding note and delete option on bookmark nowplaying page
  Backend/Backend/Migrations/20240130170726_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240130170726_firstMigration.cs
  frontend/components/nowPlaying/Bookmarks.tsx
  frontend/utilities/Interfaces.tsx
Labels: 🛠️ goal: fix

#366 Removed auth on some endpoints
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Migrations/20240130200045_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240130200045_firstMigration.cs
Labels: 🛠️ goal: fix, 🔢 points: 1, 🟨 priority: medium, Backend
