Repository awaazo/awaazo, pull requests merged in 2024-02, with the labels that each got.

#380 #379 Remove Python from CI
  Backend/Backend/Program.cs
  docker-compose.ci.yml
Labels: ✨goal: improvement, 🔢 points: 1, 🟩 priority: low, Backend

#383 Feature/chat implementation
  frontend/components/cards/EpisodeMenu.tsx
  frontend/components/explore/Episode.tsx
  frontend/components/explore/PodcastOverview.tsx
  frontend/components/explore/Subscription.tsx
  frontend/components/home/RecentlyUploaded.tsx
  frontend/components/shared/ChatBot.tsx
  frontend/components/shared/ChatBotButton.tsx
  frontend/components/shared/Sidebar.tsx
  frontend/helpers/AnnotationHelper.tsx
  frontend/helpers/AuthHelper.tsx
  frontend/helpers/BookmarksHelper.tsx
  frontend/helpers/ChatbotHelper.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/NotificationsHelper.tsx
  frontend/helpers/PodcastHelper.tsx
  frontend/helpers/SectionHelper.tsx
  frontend/helpers/SocialHelper.tsx
  frontend/helpers/SubscribeHelper.tsx
  frontend/types/Interfaces.tsx
  frontend/types/Requests.tsx
  frontend/types/Responses.tsx
  frontend/utilities/ChatBotContext.tsx
  frontend/utilities/PlayerContext.tsx
Labels: ⭐ goal: addition, 🛠️ goal: fix

#387 Improvement/transcription endpoints
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20240208182334_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240208182334_firstMigration.cs
  Backend/Backend/Models/Episode.cs
  Backend/Backend/Program.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
  Python/Dockerfile
  Python/server.py
  Python/transcription_service/stt.py
  frontend/types/Interfaces.tsx
Labels: ✨goal: improvement

#373 Refactor current auth tests
  Backend/Backend.Tests/AuthTests.cs
  Backend/Backend.Tests/ProfileTests.cs
  Backend/Backend/Migrations/20240209001923_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240209001923_firstMigration.cs
Labels: ✨goal: improvement

#385 Fixing main page and episode menu bug
  Backend/Backend/Migrations/20240209015950_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240209015950_firstMigration.cs
  Backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  frontend/components/CreatorHub/PodcastInfo.tsx
  frontend/components/cards/EpisodeCard.tsx
  frontend/components/explore/PodcastOverview.tsx
  frontend/components/home/ForYou.tsx
  frontend/components/home/PodcastTicket.tsx
  frontend/components/home/RecentlyUploaded.tsx
  frontend/components/notification/Notifications.tsx
  frontend/components/nowPlaying/Bookmarks.tsx
  frontend/components/shared/PlayerBar.tsx
  frontend/components/tools/ImageAdder.tsx
  frontend/cypress/e2e/podcast/PlayerBar.cy.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/PodcastHelper.tsx
  frontend/pages/NowPlaying/[EpisodeId].tsx
  frontend/types/Interfaces.tsx
  frontend/types/Responses.tsx
Labels: 🛠️ goal: fix

#388 Added reset password page
  frontend/components/auth/ForgotPassword.tsx
  frontend/components/auth/Login.tsx
  frontend/components/auth/ResetPassword.tsx
  frontend/components/profile/MyProfile/MyHeader.tsx
  frontend/helpers/AuthHelper.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/pages/auth/[...authPage].tsx
  frontend/types/Requests.tsx
  frontend/types/Responses.tsx
Labels: ⭐ goal: addition

#393 Added file extension validation to avatar profile for routes EditProfile and SetupProfile
  Backend/Backend.Tests/ProfileTests.cs
  Backend/Backend/Controllers/ProfileController.cs
  Backend/Backend/Infrastructure/FileStorageHelper.cs
Labels: 🛠️ goal: fix, Backend

#389 Added Endpoints for Points
  Backend/Backend.Tests/PodcastTests.cs
  Backend/Backend.Tests/WalletTests.cs
  Backend/Backend/Backend.csproj
  Backend/Backend/Controllers/Requests/StripeRequests.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Controllers/Responses/StripeResponse.cs
  Backend/Backend/Controllers/Responses/WalletResponse.cs
  Backend/Backend/Controllers/SocialController.cs
  Backend/Backend/Controllers/WalletController.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20240209015950_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240209220435_adminFlagUser.cs
  Backend/Backend/Migrations/20240210230021_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240210230021_firstMigration.cs
  Backend/Backend/Models/Episode.cs
  Backend/Backend/Models/Points.cs
  Backend/Backend/Models/Transactions.cs
  Backend/Backend/Models/User.cs
  Backend/Backend/Program.cs
  Backend/Backend/Services/Interfaces/ISocialService.cs
  Backend/Backend/Services/Interfaces/IStripeServices.cs
  Backend/Backend/Services/Interfaces/IWalletServices.cs
  Backend/Backend/Services/PodcastService.cs
  Backend/Backend/Services/SocialService.cs
  Backend/Backend/Services/StripeServices.cs
  Backend/Backend/Services/WalletServices.cs
Labels: Muhammad Mubashir 491

#382 Added API routes for Admins to GetAllUsers and to ban users
  Backend/Backend.Tests/AdminPanelTests.cs
  Backend/Backend/Controllers/AdminPanelController.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Models/User.cs
  Backend/Backend/Services/AdminPanelService.cs
Labels: SOEN 491 - 40131283 (Shadi Jiha)

#398 New migrations to fix e2e tests and code optimization
  Backend/Backend/Migrations/20240213235502_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240213235502_firstMigration.cs
  backend/Backend/Migrations/AppDbContextModelSnapshot.cs
  frontend/components/CreatorHub/EditEpisode.tsx
  frontend/components/auth/Signup.tsx
  frontend/components/explore/PodcastOverview.tsx
  frontend/components/home/ContinueListening.tsx
  frontend/components/home/PodcastTicket.tsx
  frontend/components/notification/Notifications.tsx
  frontend/components/nowPlaying/Bookmarks.tsx
  frontend/components/nowPlaying/PodCue.tsx
  frontend/components/nowPlaying/Sections.tsx
  frontend/components/playerbar/Menu.tsx
  frontend/components/playlist/AddToPlaylistModal.tsx
  frontend/components/playlist/CreatePlaylistModal.tsx
  frontend/components/playlist/PlaylistMenu.tsx
  frontend/components/playlist/PlaylistOverview.tsx
  frontend/components/playlist/ViewQueueModal.tsx
  frontend/components/profile/MyProfile/ChangePasswordForm.tsx
  frontend/components/profile/MyProfile/MyEpisodes.tsx
  frontend/components/profile/MyProfile/MyHeader.tsx
  frontend/components/profile/MyProfile/MyPlaylists.tsx
  frontend/components/profile/MyProfile/MyPodcasts.tsx
  frontend/components/profile/MyProfile/MySubscriptions.tsx
  frontend/components/profile/UserProfile/UserEpisodes.tsx
  frontend/components/profile/UserProfile/UserHeader.tsx
  frontend/components/profile/UserProfile/UserPlaylists.tsx
  frontend/components/profile/UserProfile/UserPodcasts.tsx
  frontend/pages/profile/[id].tsx
Labels: 🛠️ goal: fix

#400 fix migrations
  Backend/Backend/Migrations/20240210054547_adminEmailLogs.cs
  Backend/Backend/Migrations/20240213235502_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240216053416_MigrationMain.Designer.cs
  Backend/Backend/Migrations/20240216053416_MigrationMain.cs
  frontend/components/explore/ExploreGenres.tsx
  frontend/components/explore/Reviews.tsx
  frontend/components/home/Home.tsx
  frontend/components/shared/ChatBot.tsx
  frontend/pages/Explore/Genre/[genre].tsx
  frontend/pages/Explore/Search.tsx
Labels: 🛠️ goal: fix

#401 Adding episode transcript functionalities
  Backend/Backend/Migrations/20240221040449_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240221040449_firstMigration.cs
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/PodcastHelper.tsx
  frontend/types/Interfaces.tsx
  frontend/types/Requests.tsx
  frontend/types/Responses.tsx
Labels: ✨goal: improvement

#403 Feature/podcaster analytics endpoints
  Backend/Backend.Tests/AnalyticControllerTests.cs
  Backend/Backend.Tests/AnalyticServiceTests.cs
  Backend/Backend/Controllers/AnalyticController.cs
  Backend/Backend/Controllers/Responses/AnalyticResponses.cs
  Backend/Backend/Controllers/Responses/PodcastResponses.cs
  Backend/Backend/Infrastructure/AppDbContext.cs
  Backend/Backend/Migrations/20240222175738_firstMigration.Designer.cs
  Backend/Backend/Migrations/20240222175738_firstMigration.cs
  Backend/Backend/Models/Episode.cs
  Backend/Backend/Program.cs
  Backend/Backend/Services/AnalyticService.cs
  Backend/Backend/Services/Interfaces/IAnalyticService.cs
  Backend/Backend/Services/PodcastService.cs
  Python/requirements.txt
  backend/Backend/Migrations/AppDbContextModelSnapshot.cs
Labels: ⭐ goal: addition, Mathieu Trudeau SOEN 491

#407 Feat/comment pagination
  Backend/Backend/Controllers/Responses/SocialResponses.cs
  Backend/Backend/Controllers/SocialController.cs
  Backend/Backend/Services/Interfaces/ISocialService.cs
  Backend/Backend/Services/SocialService.cs
Labels: ✨goal: improvement, Backend

#411 Fix/episode upload
  Backend/Backend/Controllers/PodcastController.cs
  Backend/Backend/Controllers/Requests/PodcastRequests.cs
  Backend/Backend/Infrastructure/FileStorageHelper.cs
  Backend/Backend/Services/Interfaces/IPodcastService.cs
  Backend/Backend/Services/PodcastService.cs
  docker-compose.noPy.yml
  frontend/components/CreatorHub/AddEpisode.tsx
  frontend/cypress/e2e/profile/Notification.cy.tsx
  frontend/helpers/EndpointHelper.tsx
  frontend/helpers/PodcastHelper.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/types/Requests.tsx
  frontend/types/Responses.tsx
  package-lock.json
  package.json
Labels: 🛠️ goal: fix

#406 Fix/route protection
  Backend/Backend.Tests/PlaylistControllerTests.cs
  Backend/Backend/Controllers/PlaylistController.cs
  Backend/Backend/Program.cs
  Backend/Backend/Services/Interfaces/IPlaylistService.cs
  Backend/Backend/Services/PlaylistService.cs
Labels: 🛠️ goal: fix, 🧑‍💻 dev stroy
